test
Signed-off-by: Corey Hemminger <hemminger@hotmail.com>

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -158,3 +158,64 @@ jobs:
         run: |
           gem env # uncomment for testing
           bundle exec kitchen verify localhost
+
+  windows-fips-ssh:
+    env:
+      machine_port: 5985
+      KITCHEN_LOCAL_YAML: kitchen.proxy.yml
+    runs-on: windows-latest
+    timeout-minutes: 600
+    strategy:
+      fail-fast: false
+      matrix:
+        ruby: ["3.1", "3.4"]
+    steps:
+      - uses: actions/checkout@v5
+      - uses: ruby/setup-ruby@v1
+        with:
+          ruby-version: ${{ matrix.ruby }}
+          bundler-cache: true
+#       name: 'Install Chef/Ohai from Omnitruck'
+#         id: install_chef
+#         run: |
+#           . { Invoke-WebRequest -useb https://omnitruck.chef.io/install.ps1 } | Invoke-Expression; Install-Project -project chef
+#           $env:PATH = "C:\opscode\chef\bin;C:\opscode\chef\embedded\bin;" + $env:PATH
+#           chef-client -v
+#           ohai -v
+#           rake --version
+#           bundle -v
+      - name: 'Enable FIPS via windows registry' #FIPS needs to be enabled after installation of Chef, otherwise it fails due to Cryptography error
+        run: |
+          $OldErrorActionPreference = $ErrorActionPreference
+          $ErrorActionPreference = "stop"
+          $KeyPath = "HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy"
+          $ValueName = "Enabled"
+          $ValueData = "1"
+          try{
+              Get-ItemProperty -Path $KeyPath -Name $valueName -ErrorAction Stop
+              New-ItemProperty -Path $KeyPath -Name $ValueName -Value $ValueData -PropertyType DWord -Force
+          }
+          catch [System.Management.Automation.PSArgumentException] {
+              New-ItemProperty -Path $KeyPath -Name $ValueName -Value $ValueData -PropertyType DWord -Force
+          }
+          catch [System.Management.Automation.ItemNotFoundException]
+          {
+              New-Item -Path $KeyPath -Force
+              New-ItemProperty -Path $KeyPath -Name $ValueName -Value $ValueData -PropertyType DWord -Force
+          }
+          Finally
+          {
+              $ErrorActionPreference = $OldErrorActionPreference
+          }
+          if (-not $?) { throw "Failed to enable FIPS mode." }
+      - name: Setup Machine
+        run: |
+          Add-WindowsCapability -Online -Name OpenSSH.Server
+          Start-Service -Name "sshd"
+          New-NetFirewallRule -Name "OpenSSH-Server-In-TCP" -DisplayName "OpenSSH Server (sshd)" -Enabled True -Direction Inbound -Protocol TCP -LocalPort 22 -Action Allow
+          net user /add ${{ env.machine_user }} ${{ env.machine_pass }}
+          net localgroup administrators ${{ env.machine_user }} /add
+      - name: Verify Windows FIPS SSH
+        run: |
+          gem env # uncomment for testing
+          bundle exec kitchen verify windows-fips-ssh
